[tool.pytest.ini_options]
addopts = "--asyncio-mode=auto"

[tool.ruff]
select = ["E", "F", "W"]
fixable = ["ALL"]
exclude = [
    ".git",
    "venv",
    "migrations",
]
line-length = 88
# Assume Python 3.8
target-version = "py38"

[tool.black]
line-length = 88
exclude = '''
/(
  | venv
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
extend_skip = [
    "venv",
]
